baseURL = "https://spenser.io/"
defaultContentLanguage = "en"
languageCode = "en-US"
title = "Spenser Pothier"
theme = "congo"
metaDataFormat = "yaml"
uglyUrls = true

[author]
    name = "Spenser Pothier"
    image = "https://www.gravatar.com/avatar/31d03ca4600d87d851dbab4b4da40882?s=240&d=mp"
    title = "Spenser Pothier"
    description = "Site Reliability Engineer"
    links = [
        {email = "mailto:contact@spenser.io"},
        {github = "https://github.com/spenserpothier"},
        {gitlab = "https://gitlab.com/spenserpothier"},
        {Twitter = "https://twitter.com/spenserpothier"},
        {Linkedin = "https://www.linkedin.com/in/spenserpothier/"},
#        {Twitter = "https://twitter.com/spenser.in.3d"},
#        {Keybase = "https://keybase.io/spenserpothier"}
    ]
menu = ['main']
[outputs]
  home = ["HTML", "RSS", "JSON"]

[deployment]

[[deployment.targets]]
name = "s3"
URL = "s3://spenser.io?region=us-west-2"
cloudFrontDistributionID = "E1CYM5LBM47AJI"

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=2629800, no-transform, public"
gzip = true
