[[main]]
    name = "About Me"
#    pre = "<i class='fa fa-heart'></i>"
    weight = -10
    identifier = "about"
    url = "/pages/about.html"

[[main]]
    name = "Now"
    #pre = "<i class='fa fa-heart'></i>"
    weight = -20
    identifier = "Now"
    url = "/pages/now.html"

[[main]]
    name = "Blog"
    #pre = "<i class='fa fa-heart'></i>"
    weight = -20
    identifier = "Blog"
    url = "/posts.html"
